export const FETCH_MANAGERS_START = 'FETCH_MANAGERS_START';
export const FETCH_MANAGERS_SUCCESS = 'FETCH_MANAGERS_SUCCESS';
export const FETCH_MANAGERS_FAIL = 'FETCH_MANAGERS_FAIL';

export const REMOVE_MANAGER_START = 'REMOVE_MANAGER_START';
export const REMOVE_MANAGER_FAIL = 'REMOVE_MANAGER_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS= 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';